export const doctorInfo = {
  SPECIALTIES: [
    "Cardiología",
    "Neurología",
    "Oftalmología",
    "Dermatología",
    "Ginecología",
    "Pediatría",
    "Ortopedia",
    "Urología",
    "Endocrinología",
    "Psiquiatría",
  ],
  FACULTIES: [
    "Facultad de Ciencias Médicas Avanzadas",
    "Facultad de Medicina Innovadora",
    "Facultad de Salud Integral",
    "Escuela de Ciencias Médicas Vanguardia",
    "Facultad de Investigación Médica",
    "Instituto de Ciencias de la Salud Futura",
    "Facultad de Medicina Integrativa",
    "Instituto de Ciencias Biomédicas Progresivas",
    "Facultad de Salud Global",
    "Escuela de Medicina Avanzada",
  ],
  MEDICAL_LICENSES: [
    "Licencia Médica General",
    "Licencia de Especialidad",
    "Licencia de Cirugía",
    "Licencia de Investigación Médica",
    "Licencia de Docencia Médica",
    "Licencia de Terapia Física",
    "Licencia de Psicoterapia Médica",
    "Licencia de Medicina Preventiva",
    "Licencia de Radiología Médica",
    "Licencia de Medicina Deportiva",
  ],
};

export const employeeInfo = {
  CLINIC_POSITIONS: [
    "Jefe de Departamento",
    "Médico Senior",
    "Enfermero Jefe",
    "Director Médico",
    "Coordinador de Investigación",
    "Jefe de Cirugía",
    "Supervisor de Enfermería",
    "Especialista en Emergencias",
    "Jefe de Laboratorio",
    "Director de Salud Mental",
  ],
  ACADEMIC_DEGREES: [
    "Doctor en Medicina",
    "Maestría en Salud Pública",
    "Especialización en Cirugía",
    "Maestría en Investigación Médica",
    "Doctorado en Ciencias Biomédicas",
    "Especialización en Salud Mental",
    "Maestría en Geriatría",
    "Doctorado en Genética Médica",
    "Especialización en Medicina Deportiva",
    "Maestría en Bioética Médica",
  ],
};
